resources:
  - name: ios-dummy
    type: git
    source:
      uri: https://github.com/melbourne-eng-recruitment/ios-concourse
      branch: master

jobs:
  - name: ios-dummy
    plan:
      - get: ios-dummy
        trigger: true
      - task: specs
        config:
          platform: darwin
          inputs:
            - name: ios-dummy
          run:
            path: bash
            user: mark.boulton
            args:
              - "-c"
              - "cd ios-dummy/ProjectFoDummies && fastlane test"
